// swift-tools-version: 5.9
import PackageDescription

private let targets: [Target] = [
        .target(name: "Pkg1Target1"),
        .target(name: "Pkg1Target2"),
        .target(name: "Pkg1Target3"),
        .target(name: "Pkg1Target4"),
        .target(name: "Pkg1Target5"),
        .target(name: "Pkg1Target6"),
        .target(name: "Pkg1Target7"),
        .target(name: "Pkg1Target8"),
        .target(name: "Pkg1Target9"),
        .target(name: "Pkg1Target10"),
        .target(name: "Pkg1Target11"),
        .target(name: "Pkg1Target12"),
        .target(name: "Pkg1Target13"),
        .target(name: "Pkg1Target14"),
        .target(name: "Pkg1Target15"),
        .target(name: "Pkg1Target16"),
        .target(name: "Pkg1Target17"),
        .target(name: "Pkg1Target18"),
        .target(name: "Pkg1Target19"),
        .target(name: "Pkg1Target20"),
        .target(name: "Pkg1Target21"),
        .target(name: "Pkg1Target22"),
        .target(name: "Pkg1Target23"),
        .target(name: "Pkg1Target24"),
        .target(name: "Pkg1Target25"),
        .target(name: "Pkg1Target26"),
        .target(name: "Pkg1Target27"),
        .target(name: "Pkg1Target28"),
        .target(name: "Pkg1Target29"),
        .target(name: "Pkg1Target30"),
        .target(name: "Pkg1Target31"),
        .target(name: "Pkg1Target32"),
        .target(name: "Pkg1Target33"),
        .target(name: "Pkg1Target34"),
        .target(name: "Pkg1Target35"),
        .target(name: "Pkg1Target36"),
        .target(name: "Pkg1Target37"),
        .target(name: "Pkg1Target38"),
        .target(name: "Pkg1Target39"),
        .target(name: "Pkg1Target40"),
        .target(name: "Pkg1Target41"),
        .target(name: "Pkg1Target42"),
        .target(name: "Pkg1Target43"),
        .target(name: "Pkg1Target44"),
        .target(name: "Pkg1Target45"),
        .target(name: "Pkg1Target46"),
        .target(name: "Pkg1Target47"),
        .target(name: "Pkg1Target48"),
        .target(name: "Pkg1Target49"),
        .target(name: "Pkg1Target50"),
        .target(name: "Pkg1Target51"),
        .target(name: "Pkg1Target52"),
        .target(name: "Pkg1Target53"),
        .target(name: "Pkg1Target54"),
        .target(name: "Pkg1Target55"),
        .target(name: "Pkg1Target56"),
        .target(name: "Pkg1Target57"),
        .target(name: "Pkg1Target58"),
        .target(name: "Pkg1Target59"),
        .target(name: "Pkg1Target60"),
        .target(name: "Pkg1Target61"),
        .target(name: "Pkg1Target62"),
        .target(name: "Pkg1Target63"),
        .target(name: "Pkg1Target64"),
        .target(name: "Pkg1Target65"),
        .target(name: "Pkg1Target66"),
        .target(name: "Pkg1Target67"),
        .target(name: "Pkg1Target68"),
        .target(name: "Pkg1Target69"),
        .target(name: "Pkg1Target70"),
        .target(name: "Pkg1Target71"),
        .target(name: "Pkg1Target72"),
        .target(name: "Pkg1Target73"),
        .target(name: "Pkg1Target74"),
        .target(name: "Pkg1Target75"),
        .target(name: "Pkg1Target76"),
        .target(name: "Pkg1Target77"),
        .target(name: "Pkg1Target78"),
        .target(name: "Pkg1Target79"),
        .target(name: "Pkg1Target80"),
        .target(name: "Pkg1Target81"),
        .target(name: "Pkg1Target82"),
        .target(name: "Pkg1Target83"),
        .target(name: "Pkg1Target84"),
        .target(name: "Pkg1Target85"),
        .target(name: "Pkg1Target86"),
        .target(name: "Pkg1Target87"),
        .target(name: "Pkg1Target88"),
        .target(name: "Pkg1Target89"),
        .target(name: "Pkg1Target90"),
        .target(name: "Pkg1Target91"),
        .target(name: "Pkg1Target92"),
        .target(name: "Pkg1Target93"),
        .target(name: "Pkg1Target94"),
        .target(name: "Pkg1Target95"),
        .target(name: "Pkg1Target96"),
        .target(name: "Pkg1Target97"),
        .target(name: "Pkg1Target98"),
        .target(name: "Pkg1Target99"),
        .target(name: "Pkg1Target100"),
        .target(name: "Pkg1Target101"),
        .target(name: "Pkg1Target102"),
        .target(name: "Pkg1Target103"),
        .target(name: "Pkg1Target104"),
        .target(name: "Pkg1Target105"),
        .target(name: "Pkg1Target106"),
        .target(name: "Pkg1Target107"),
        .target(name: "Pkg1Target108"),
        .target(name: "Pkg1Target109"),
        .target(name: "Pkg1Target110"),
        .target(name: "Pkg1Target111"),
        .target(name: "Pkg1Target112"),
        .target(name: "Pkg1Target113"),
        .target(name: "Pkg1Target114"),
        .target(name: "Pkg1Target115"),
        .target(name: "Pkg1Target116"),
        .target(name: "Pkg1Target117"),
        .target(name: "Pkg1Target118"),
        .target(name: "Pkg1Target119"),
        .target(name: "Pkg1Target120"),
        .target(name: "Pkg1Target121"),
        .target(name: "Pkg1Target122"),
        .target(name: "Pkg1Target123"),
        .target(name: "Pkg1Target124"),
        .target(name: "Pkg1Target125"),
        .target(name: "Pkg1Target126"),
        .target(name: "Pkg1Target127"),
        .target(name: "Pkg1Target128"),
        .target(name: "Pkg1Target129"),
        .target(name: "Pkg1Target130"),
        .target(name: "Pkg1Target131"),
        .target(name: "Pkg1Target132"),
        .target(name: "Pkg1Target133"),
        .target(name: "Pkg1Target134"),
        .target(name: "Pkg1Target135"),
        .target(name: "Pkg1Target136"),
        .target(name: "Pkg1Target137"),
        .target(name: "Pkg1Target138"),
        .target(name: "Pkg1Target139"),
        .target(name: "Pkg1Target140"),
        .target(name: "Pkg1Target141"),
        .target(name: "Pkg1Target142"),
        .target(name: "Pkg1Target143"),
        .target(name: "Pkg1Target144"),
        .target(name: "Pkg1Target145"),
        .target(name: "Pkg1Target146"),
        .target(name: "Pkg1Target147"),
        .target(name: "Pkg1Target148"),
        .target(name: "Pkg1Target149"),
        .target(name: "Pkg1Target150"),
        .target(name: "Pkg1Target151"),
        .target(name: "Pkg1Target152"),
        .target(name: "Pkg1Target153"),
        .target(name: "Pkg1Target154"),
        .target(name: "Pkg1Target155"),
        .target(name: "Pkg1Target156"),
        .target(name: "Pkg1Target157"),
        .target(name: "Pkg1Target158"),
        .target(name: "Pkg1Target159"),
        .target(name: "Pkg1Target160"),
        .target(name: "Pkg1Target161"),
        .target(name: "Pkg1Target162"),
        .target(name: "Pkg1Target163"),
        .target(name: "Pkg1Target164"),
        .target(name: "Pkg1Target165"),
        .target(name: "Pkg1Target166"),
        .target(name: "Pkg1Target167"),
        .target(name: "Pkg1Target168"),
        .target(name: "Pkg1Target169"),
        .target(name: "Pkg1Target170"),
        .target(name: "Pkg1Target171"),
        .target(name: "Pkg1Target172"),
        .target(name: "Pkg1Target173"),
        .target(name: "Pkg1Target174"),
        .target(name: "Pkg1Target175"),
        .target(name: "Pkg1Target176"),
        .target(name: "Pkg1Target177"),
        .target(name: "Pkg1Target178"),
        .target(name: "Pkg1Target179"),
        .target(name: "Pkg1Target180"),
        .target(name: "Pkg1Target181"),
        .target(name: "Pkg1Target182"),
        .target(name: "Pkg1Target183"),
        .target(name: "Pkg1Target184"),
        .target(name: "Pkg1Target185"),
        .target(name: "Pkg1Target186"),
        .target(name: "Pkg1Target187"),
        .target(name: "Pkg1Target188"),
        .target(name: "Pkg1Target189"),
        .target(name: "Pkg1Target190"),
        .target(name: "Pkg1Target191"),
        .target(name: "Pkg1Target192"),
        .target(name: "Pkg1Target193"),
        .target(name: "Pkg1Target194"),
        .target(name: "Pkg1Target195"),
        .target(name: "Pkg1Target196"),
        .target(name: "Pkg1Target197"),
        .target(name: "Pkg1Target198"),
        .target(name: "Pkg1Target199"),
        .target(name: "Pkg1Target200"),
        .target(name: "Pkg1Target201"),
        .target(name: "Pkg1Target202"),
        .target(name: "Pkg1Target203"),
        .target(name: "Pkg1Target204"),
        .target(name: "Pkg1Target205"),
        .target(name: "Pkg1Target206"),
        .target(name: "Pkg1Target207"),
        .target(name: "Pkg1Target208"),
        .target(name: "Pkg1Target209"),
        .target(name: "Pkg1Target210"),
        .target(name: "Pkg1Target211"),
        .target(name: "Pkg1Target212"),
        .target(name: "Pkg1Target213"),
        .target(name: "Pkg1Target214"),
        .target(name: "Pkg1Target215"),
        .target(name: "Pkg1Target216"),
        .target(name: "Pkg1Target217"),
        .target(name: "Pkg1Target218"),
        .target(name: "Pkg1Target219"),
        .target(name: "Pkg1Target220"),
        .target(name: "Pkg1Target221"),
        .target(name: "Pkg1Target222"),
        .target(name: "Pkg1Target223"),
        .target(name: "Pkg1Target224"),
        .target(name: "Pkg1Target225"),
        .target(name: "Pkg1Target226"),
        .target(name: "Pkg1Target227"),
        .target(name: "Pkg1Target228"),
        .target(name: "Pkg1Target229"),
        .target(name: "Pkg1Target230"),
        .target(name: "Pkg1Target231"),
        .target(name: "Pkg1Target232"),
        .target(name: "Pkg1Target233"),
        .target(name: "Pkg1Target234"),
        .target(name: "Pkg1Target235"),
        .target(name: "Pkg1Target236"),
        .target(name: "Pkg1Target237"),
        .target(name: "Pkg1Target238"),
        .target(name: "Pkg1Target239"),
        .target(name: "Pkg1Target240"),
        .target(name: "Pkg1Target241"),
        .target(name: "Pkg1Target242"),
        .target(name: "Pkg1Target243"),
        .target(name: "Pkg1Target244"),
        .target(name: "Pkg1Target245"),
        .target(name: "Pkg1Target246"),
        .target(name: "Pkg1Target247"),
        .target(name: "Pkg1Target248"),
        .target(name: "Pkg1Target249"),
        .target(name: "Pkg1Target250"),
        .target(name: "Pkg1Target251"),
        .target(name: "Pkg1Target252"),
        .target(name: "Pkg1Target253"),
        .target(name: "Pkg1Target254"),
        .target(name: "Pkg1Target255"),
        .target(name: "Pkg1Target256"),
        .target(name: "Pkg1Target257"),
        .target(name: "Pkg1Target258"),
        .target(name: "Pkg1Target259"),
        .target(name: "Pkg1Target260"),
        .target(name: "Pkg1Target261"),
        .target(name: "Pkg1Target262"),
        .target(name: "Pkg1Target263"),
        .target(name: "Pkg1Target264"),
        .target(name: "Pkg1Target265"),
        .target(name: "Pkg1Target266"),
        .target(name: "Pkg1Target267"),
        .target(name: "Pkg1Target268"),
        .target(name: "Pkg1Target269"),
        .target(name: "Pkg1Target270"),
        .target(name: "Pkg1Target271"),
        .target(name: "Pkg1Target272"),
        .target(name: "Pkg1Target273"),
        .target(name: "Pkg1Target274"),
        .target(name: "Pkg1Target275"),
        .target(name: "Pkg1Target276"),
        .target(name: "Pkg1Target277"),
        .target(name: "Pkg1Target278"),
        .target(name: "Pkg1Target279"),
        .target(name: "Pkg1Target280"),
        .target(name: "Pkg1Target281"),
        .target(name: "Pkg1Target282"),
        .target(name: "Pkg1Target283"),
        .target(name: "Pkg1Target284"),
        .target(name: "Pkg1Target285"),
        .target(name: "Pkg1Target286"),
        .target(name: "Pkg1Target287"),
        .target(name: "Pkg1Target288"),
        .target(name: "Pkg1Target289"),
        .target(name: "Pkg1Target290"),
        .target(name: "Pkg1Target291"),
        .target(name: "Pkg1Target292"),
        .target(name: "Pkg1Target293"),
        .target(name: "Pkg1Target294"),
        .target(name: "Pkg1Target295"),
        .target(name: "Pkg1Target296"),
        .target(name: "Pkg1Target297"),
        .target(name: "Pkg1Target298"),
        .target(name: "Pkg1Target299"),
        .target(name: "Pkg1Target300"),
        .target(name: "Pkg1Target301"),
        .target(name: "Pkg1Target302"),
        .target(name: "Pkg1Target303"),
        .target(name: "Pkg1Target304"),
        .target(name: "Pkg1Target305"),
        .target(name: "Pkg1Target306"),
        .target(name: "Pkg1Target307"),
        .target(name: "Pkg1Target308"),
        .target(name: "Pkg1Target309"),
        .target(name: "Pkg1Target310"),
        .target(name: "Pkg1Target311"),
        .target(name: "Pkg1Target312"),
        .target(name: "Pkg1Target313"),
        .target(name: "Pkg1Target314"),
        .target(name: "Pkg1Target315"),
        .target(name: "Pkg1Target316"),
        .target(name: "Pkg1Target317"),
        .target(name: "Pkg1Target318"),
        .target(name: "Pkg1Target319"),
        .target(name: "Pkg1Target320"),
        .target(name: "Pkg1Target321"),
        .target(name: "Pkg1Target322"),
        .target(name: "Pkg1Target323"),
        .target(name: "Pkg1Target324"),
        .target(name: "Pkg1Target325"),
        .target(name: "Pkg1Target326"),
        .target(name: "Pkg1Target327"),
        .target(name: "Pkg1Target328"),
        .target(name: "Pkg1Target329"),
        .target(name: "Pkg1Target330"),
        .target(name: "Pkg1Target331"),
        .target(name: "Pkg1Target332"),
        .target(name: "Pkg1Target333"),
        .target(name: "Pkg1Target334"),
        .target(name: "Pkg1Target335"),
        .target(name: "Pkg1Target336"),
        .target(name: "Pkg1Target337"),
        .target(name: "Pkg1Target338"),
        .target(name: "Pkg1Target339"),
        .target(name: "Pkg1Target340"),
        .target(name: "Pkg1Target341"),
        .target(name: "Pkg1Target342"),
        .target(name: "Pkg1Target343"),
        .target(name: "Pkg1Target344"),
        .target(name: "Pkg1Target345"),
        .target(name: "Pkg1Target346"),
        .target(name: "Pkg1Target347"),
        .target(name: "Pkg1Target348"),
        .target(name: "Pkg1Target349"),
        .target(name: "Pkg1Target350"),
        .target(name: "Pkg1Target351"),
        .target(name: "Pkg1Target352"),
        .target(name: "Pkg1Target353"),
        .target(name: "Pkg1Target354"),
        .target(name: "Pkg1Target355"),
        .target(name: "Pkg1Target356"),
        .target(name: "Pkg1Target357"),
        .target(name: "Pkg1Target358"),
        .target(name: "Pkg1Target359"),
        .target(name: "Pkg1Target360"),
        .target(name: "Pkg1Target361"),
        .target(name: "Pkg1Target362"),
        .target(name: "Pkg1Target363"),
        .target(name: "Pkg1Target364"),
        .target(name: "Pkg1Target365"),
        .target(name: "Pkg1Target366"),
        .target(name: "Pkg1Target367"),
        .target(name: "Pkg1Target368"),
        .target(name: "Pkg1Target369"),
        .target(name: "Pkg1Target370"),
        .target(name: "Pkg1Target371"),
        .target(name: "Pkg1Target372"),
        .target(name: "Pkg1Target373"),
        .target(name: "Pkg1Target374"),
        .target(name: "Pkg1Target375"),
        .target(name: "Pkg1Target376"),
        .target(name: "Pkg1Target377"),
        .target(name: "Pkg1Target378"),
        .target(name: "Pkg1Target379"),
        .target(name: "Pkg1Target380"),
        .target(name: "Pkg1Target381"),
        .target(name: "Pkg1Target382"),
        .target(name: "Pkg1Target383"),
        .target(name: "Pkg1Target384"),
        .target(name: "Pkg1Target385"),
        .target(name: "Pkg1Target386"),
        .target(name: "Pkg1Target387"),
        .target(name: "Pkg1Target388"),
        .target(name: "Pkg1Target389"),
        .target(name: "Pkg1Target390"),
        .target(name: "Pkg1Target391"),
        .target(name: "Pkg1Target392"),
        .target(name: "Pkg1Target393"),
        .target(name: "Pkg1Target394"),
        .target(name: "Pkg1Target395"),
        .target(name: "Pkg1Target396"),
        .target(name: "Pkg1Target397"),
        .target(name: "Pkg1Target398"),
        .target(name: "Pkg1Target399"),
        .target(name: "Pkg1Target400"),
        .target(name: "Pkg1Target401"),
        .target(name: "Pkg1Target402"),
        .target(name: "Pkg1Target403"),
        .target(name: "Pkg1Target404"),
        .target(name: "Pkg1Target405"),
        .target(name: "Pkg1Target406"),
        .target(name: "Pkg1Target407"),
        .target(name: "Pkg1Target408"),
        .target(name: "Pkg1Target409"),
        .target(name: "Pkg1Target410"),
        .target(name: "Pkg1Target411"),
        .target(name: "Pkg1Target412"),
        .target(name: "Pkg1Target413"),
        .target(name: "Pkg1Target414"),
        .target(name: "Pkg1Target415"),
        .target(name: "Pkg1Target416"),
        .target(name: "Pkg1Target417"),
        .target(name: "Pkg1Target418"),
        .target(name: "Pkg1Target419"),
        .target(name: "Pkg1Target420"),
        .target(name: "Pkg1Target421"),
        .target(name: "Pkg1Target422"),
        .target(name: "Pkg1Target423"),
        .target(name: "Pkg1Target424"),
        .target(name: "Pkg1Target425"),
        .target(name: "Pkg1Target426"),
        .target(name: "Pkg1Target427"),
        .target(name: "Pkg1Target428"),
        .target(name: "Pkg1Target429"),
        .target(name: "Pkg1Target430"),
        .target(name: "Pkg1Target431"),
        .target(name: "Pkg1Target432"),
        .target(name: "Pkg1Target433"),
        .target(name: "Pkg1Target434"),
        .target(name: "Pkg1Target435"),
        .target(name: "Pkg1Target436"),
        .target(name: "Pkg1Target437"),
        .target(name: "Pkg1Target438"),
        .target(name: "Pkg1Target439"),
        .target(name: "Pkg1Target440"),
        .target(name: "Pkg1Target441"),
        .target(name: "Pkg1Target442"),
        .target(name: "Pkg1Target443"),
        .target(name: "Pkg1Target444"),
        .target(name: "Pkg1Target445"),
        .target(name: "Pkg1Target446"),
        .target(name: "Pkg1Target447"),
        .target(name: "Pkg1Target448"),
        .target(name: "Pkg1Target449"),
        .target(name: "Pkg1Target450"),
        .target(name: "Pkg1Target451"),
        .target(name: "Pkg1Target452"),
        .target(name: "Pkg1Target453"),
        .target(name: "Pkg1Target454"),
        .target(name: "Pkg1Target455"),
        .target(name: "Pkg1Target456"),
        .target(name: "Pkg1Target457"),
        .target(name: "Pkg1Target458"),
        .target(name: "Pkg1Target459"),
        .target(name: "Pkg1Target460"),
        .target(name: "Pkg1Target461"),
        .target(name: "Pkg1Target462"),
        .target(name: "Pkg1Target463"),
        .target(name: "Pkg1Target464"),
        .target(name: "Pkg1Target465"),
        .target(name: "Pkg1Target466"),
        .target(name: "Pkg1Target467"),
        .target(name: "Pkg1Target468"),
        .target(name: "Pkg1Target469"),
        .target(name: "Pkg1Target470"),
        .target(name: "Pkg1Target471"),
        .target(name: "Pkg1Target472"),
        .target(name: "Pkg1Target473"),
        .target(name: "Pkg1Target474"),
        .target(name: "Pkg1Target475"),
        .target(name: "Pkg1Target476"),
        .target(name: "Pkg1Target477"),
        .target(name: "Pkg1Target478"),
        .target(name: "Pkg1Target479"),
        .target(name: "Pkg1Target480"),
        .target(name: "Pkg1Target481"),
        .target(name: "Pkg1Target482"),
        .target(name: "Pkg1Target483"),
        .target(name: "Pkg1Target484"),
        .target(name: "Pkg1Target485"),
        .target(name: "Pkg1Target486"),
        .target(name: "Pkg1Target487"),
        .target(name: "Pkg1Target488"),
        .target(name: "Pkg1Target489"),
        .target(name: "Pkg1Target490"),
        .target(name: "Pkg1Target491"),
        .target(name: "Pkg1Target492"),
        .target(name: "Pkg1Target493"),
        .target(name: "Pkg1Target494"),
        .target(name: "Pkg1Target495"),
        .target(name: "Pkg1Target496"),
        .target(name: "Pkg1Target497"),
        .target(name: "Pkg1Target498"),
        .target(name: "Pkg1Target499"),
        .target(name: "Pkg1Target500"),
        .target(name: "Pkg1Target501"),
        .target(name: "Pkg1Target502"),
        .target(name: "Pkg1Target503"),
        .target(name: "Pkg1Target504"),
        .target(name: "Pkg1Target505"),
        .target(name: "Pkg1Target506"),
        .target(name: "Pkg1Target507"),
        .target(name: "Pkg1Target508"),
        .target(name: "Pkg1Target509"),
        .target(name: "Pkg1Target510"),
        .target(name: "Pkg1Target511"),
        .target(name: "Pkg1Target512"),
        .target(name: "Pkg1Target513"),
        .target(name: "Pkg1Target514"),
        .target(name: "Pkg1Target515"),
        .target(name: "Pkg1Target516"),
        .target(name: "Pkg1Target517"),
        .target(name: "Pkg1Target518"),
        .target(name: "Pkg1Target519"),
        .target(name: "Pkg1Target520"),
        .target(name: "Pkg1Target521"),
        .target(name: "Pkg1Target522"),
        .target(name: "Pkg1Target523"),
        .target(name: "Pkg1Target524"),
        .target(name: "Pkg1Target525"),
        .target(name: "Pkg1Target526"),
        .target(name: "Pkg1Target527"),
        .target(name: "Pkg1Target528"),
        .target(name: "Pkg1Target529"),
        .target(name: "Pkg1Target530"),
        .target(name: "Pkg1Target531"),
        .target(name: "Pkg1Target532"),
        .target(name: "Pkg1Target533"),
        .target(name: "Pkg1Target534"),
        .target(name: "Pkg1Target535"),
        .target(name: "Pkg1Target536"),
        .target(name: "Pkg1Target537"),
        .target(name: "Pkg1Target538"),
        .target(name: "Pkg1Target539"),
        .target(name: "Pkg1Target540"),
        .target(name: "Pkg1Target541"),
        .target(name: "Pkg1Target542"),
        .target(name: "Pkg1Target543"),
        .target(name: "Pkg1Target544"),
        .target(name: "Pkg1Target545"),
        .target(name: "Pkg1Target546"),
        .target(name: "Pkg1Target547"),
        .target(name: "Pkg1Target548"),
        .target(name: "Pkg1Target549"),
        .target(name: "Pkg1Target550"),
        .target(name: "Pkg1Target551"),
        .target(name: "Pkg1Target552"),
        .target(name: "Pkg1Target553"),
        .target(name: "Pkg1Target554"),
        .target(name: "Pkg1Target555"),
        .target(name: "Pkg1Target556"),
        .target(name: "Pkg1Target557"),
        .target(name: "Pkg1Target558"),
        .target(name: "Pkg1Target559"),
        .target(name: "Pkg1Target560"),
        .target(name: "Pkg1Target561"),
        .target(name: "Pkg1Target562"),
        .target(name: "Pkg1Target563"),
        .target(name: "Pkg1Target564"),
        .target(name: "Pkg1Target565"),
        .target(name: "Pkg1Target566"),
        .target(name: "Pkg1Target567"),
        .target(name: "Pkg1Target568"),
        .target(name: "Pkg1Target569"),
        .target(name: "Pkg1Target570"),
        .target(name: "Pkg1Target571"),
        .target(name: "Pkg1Target572"),
        .target(name: "Pkg1Target573"),
        .target(name: "Pkg1Target574"),
        .target(name: "Pkg1Target575"),
        .target(name: "Pkg1Target576"),
        .target(name: "Pkg1Target577"),
        .target(name: "Pkg1Target578"),
        .target(name: "Pkg1Target579"),
        .target(name: "Pkg1Target580"),
        .target(name: "Pkg1Target581"),
        .target(name: "Pkg1Target582"),
        .target(name: "Pkg1Target583"),
        .target(name: "Pkg1Target584"),
        .target(name: "Pkg1Target585"),
        .target(name: "Pkg1Target586"),
        .target(name: "Pkg1Target587"),
        .target(name: "Pkg1Target588"),
        .target(name: "Pkg1Target589"),
        .target(name: "Pkg1Target590"),
        .target(name: "Pkg1Target591"),
        .target(name: "Pkg1Target592"),
        .target(name: "Pkg1Target593"),
        .target(name: "Pkg1Target594"),
        .target(name: "Pkg1Target595"),
        .target(name: "Pkg1Target596"),
        .target(name: "Pkg1Target597"),
        .target(name: "Pkg1Target598"),
        .target(name: "Pkg1Target599"),
        .target(name: "Pkg1Target600"),
        .target(name: "Pkg1Target601"),
        .target(name: "Pkg1Target602"),
        .target(name: "Pkg1Target603"),
        .target(name: "Pkg1Target604"),
        .target(name: "Pkg1Target605"),
        .target(name: "Pkg1Target606"),
        .target(name: "Pkg1Target607"),
        .target(name: "Pkg1Target608"),
        .target(name: "Pkg1Target609"),
        .target(name: "Pkg1Target610"),
        .target(name: "Pkg1Target611"),
        .target(name: "Pkg1Target612"),
        .target(name: "Pkg1Target613"),
        .target(name: "Pkg1Target614"),
        .target(name: "Pkg1Target615"),
        .target(name: "Pkg1Target616"),
        .target(name: "Pkg1Target617"),
        .target(name: "Pkg1Target618"),
        .target(name: "Pkg1Target619"),
        .target(name: "Pkg1Target620"),
        .target(name: "Pkg1Target621"),
        .target(name: "Pkg1Target622"),
        .target(name: "Pkg1Target623"),
        .target(name: "Pkg1Target624"),
        .target(name: "Pkg1Target625"),
        .target(name: "Pkg1Target626"),
        .target(name: "Pkg1Target627"),
        .target(name: "Pkg1Target628"),
        .target(name: "Pkg1Target629"),
        .target(name: "Pkg1Target630"),
        .target(name: "Pkg1Target631"),
        .target(name: "Pkg1Target632"),
        .target(name: "Pkg1Target633"),
        .target(name: "Pkg1Target634"),
        .target(name: "Pkg1Target635"),
        .target(name: "Pkg1Target636"),
        .target(name: "Pkg1Target637"),
        .target(name: "Pkg1Target638"),
        .target(name: "Pkg1Target639"),
        .target(name: "Pkg1Target640"),
        .target(name: "Pkg1Target641"),
        .target(name: "Pkg1Target642"),
        .target(name: "Pkg1Target643"),
        .target(name: "Pkg1Target644"),
        .target(name: "Pkg1Target645"),
        .target(name: "Pkg1Target646"),
        .target(name: "Pkg1Target647"),
        .target(name: "Pkg1Target648"),
        .target(name: "Pkg1Target649"),
        .target(name: "Pkg1Target650"),
        .target(name: "Pkg1Target651"),
        .target(name: "Pkg1Target652"),
        .target(name: "Pkg1Target653"),
        .target(name: "Pkg1Target654"),
        .target(name: "Pkg1Target655"),
        .target(name: "Pkg1Target656"),
        .target(name: "Pkg1Target657"),
        .target(name: "Pkg1Target658"),
        .target(name: "Pkg1Target659"),
        .target(name: "Pkg1Target660"),
        .target(name: "Pkg1Target661"),
        .target(name: "Pkg1Target662"),
        .target(name: "Pkg1Target663"),
        .target(name: "Pkg1Target664"),
        .target(name: "Pkg1Target665"),
        .target(name: "Pkg1Target666"),
        .target(name: "Pkg1Target667"),
        .target(name: "Pkg1Target668"),
        .target(name: "Pkg1Target669"),
        .target(name: "Pkg1Target670"),
        .target(name: "Pkg1Target671"),
        .target(name: "Pkg1Target672"),
        .target(name: "Pkg1Target673"),
        .target(name: "Pkg1Target674"),
        .target(name: "Pkg1Target675"),
        .target(name: "Pkg1Target676"),
        .target(name: "Pkg1Target677"),
        .target(name: "Pkg1Target678"),
        .target(name: "Pkg1Target679"),
        .target(name: "Pkg1Target680"),
        .target(name: "Pkg1Target681"),
        .target(name: "Pkg1Target682"),
        .target(name: "Pkg1Target683"),
        .target(name: "Pkg1Target684"),
        .target(name: "Pkg1Target685"),
        .target(name: "Pkg1Target686"),
        .target(name: "Pkg1Target687"),
        .target(name: "Pkg1Target688"),
        .target(name: "Pkg1Target689"),
        .target(name: "Pkg1Target690"),
        .target(name: "Pkg1Target691"),
        .target(name: "Pkg1Target692"),
        .target(name: "Pkg1Target693"),
        .target(name: "Pkg1Target694"),
        .target(name: "Pkg1Target695"),
        .target(name: "Pkg1Target696"),
        .target(name: "Pkg1Target697"),
        .target(name: "Pkg1Target698"),
        .target(name: "Pkg1Target699"),
        .target(name: "Pkg1Target700"),
        .target(name: "Pkg1Target701"),
        .target(name: "Pkg1Target702"),
        .target(name: "Pkg1Target703"),
        .target(name: "Pkg1Target704"),
        .target(name: "Pkg1Target705"),
        .target(name: "Pkg1Target706"),
        .target(name: "Pkg1Target707"),
        .target(name: "Pkg1Target708"),
        .target(name: "Pkg1Target709"),
        .target(name: "Pkg1Target710"),
        .target(name: "Pkg1Target711"),
        .target(name: "Pkg1Target712"),
        .target(name: "Pkg1Target713"),
        .target(name: "Pkg1Target714"),
        .target(name: "Pkg1Target715"),
        .target(name: "Pkg1Target716"),
        .target(name: "Pkg1Target717"),
        .target(name: "Pkg1Target718"),
        .target(name: "Pkg1Target719"),
        .target(name: "Pkg1Target720"),
        .target(name: "Pkg1Target721"),
        .target(name: "Pkg1Target722"),
        .target(name: "Pkg1Target723"),
        .target(name: "Pkg1Target724"),
        .target(name: "Pkg1Target725"),
        .target(name: "Pkg1Target726"),
        .target(name: "Pkg1Target727"),
        .target(name: "Pkg1Target728"),
        .target(name: "Pkg1Target729"),
        .target(name: "Pkg1Target730"),
        .target(name: "Pkg1Target731"),
        .target(name: "Pkg1Target732"),
        .target(name: "Pkg1Target733"),
        .target(name: "Pkg1Target734"),
        .target(name: "Pkg1Target735"),
        .target(name: "Pkg1Target736"),
        .target(name: "Pkg1Target737"),
        .target(name: "Pkg1Target738"),
        .target(name: "Pkg1Target739"),
        .target(name: "Pkg1Target740"),
        .target(name: "Pkg1Target741"),
        .target(name: "Pkg1Target742"),
        .target(name: "Pkg1Target743"),
        .target(name: "Pkg1Target744"),
        .target(name: "Pkg1Target745"),
        .target(name: "Pkg1Target746"),
        .target(name: "Pkg1Target747"),
        .target(name: "Pkg1Target748"),
        .target(name: "Pkg1Target749"),
        .target(name: "Pkg1Target750"),
        .target(name: "Pkg1Target751"),
        .target(name: "Pkg1Target752"),
        .target(name: "Pkg1Target753"),
        .target(name: "Pkg1Target754"),
        .target(name: "Pkg1Target755"),
        .target(name: "Pkg1Target756"),
        .target(name: "Pkg1Target757"),
        .target(name: "Pkg1Target758"),
        .target(name: "Pkg1Target759"),
        .target(name: "Pkg1Target760"),
        .target(name: "Pkg1Target761"),
        .target(name: "Pkg1Target762"),
        .target(name: "Pkg1Target763"),
        .target(name: "Pkg1Target764"),
        .target(name: "Pkg1Target765"),
        .target(name: "Pkg1Target766"),
        .target(name: "Pkg1Target767"),
        .target(name: "Pkg1Target768"),
        .target(name: "Pkg1Target769"),
        .target(name: "Pkg1Target770"),
        .target(name: "Pkg1Target771"),
        .target(name: "Pkg1Target772"),
        .target(name: "Pkg1Target773"),
        .target(name: "Pkg1Target774"),
        .target(name: "Pkg1Target775"),
        .target(name: "Pkg1Target776"),
        .target(name: "Pkg1Target777"),
        .target(name: "Pkg1Target778"),
        .target(name: "Pkg1Target779"),
        .target(name: "Pkg1Target780"),
        .target(name: "Pkg1Target781"),
        .target(name: "Pkg1Target782"),
        .target(name: "Pkg1Target783"),
        .target(name: "Pkg1Target784"),
        .target(name: "Pkg1Target785"),
        .target(name: "Pkg1Target786"),
        .target(name: "Pkg1Target787"),
        .target(name: "Pkg1Target788"),
        .target(name: "Pkg1Target789"),
        .target(name: "Pkg1Target790"),
        .target(name: "Pkg1Target791"),
        .target(name: "Pkg1Target792"),
        .target(name: "Pkg1Target793"),
        .target(name: "Pkg1Target794"),
        .target(name: "Pkg1Target795"),
        .target(name: "Pkg1Target796"),
        .target(name: "Pkg1Target797"),
        .target(name: "Pkg1Target798"),
        .target(name: "Pkg1Target799"),
        .target(name: "Pkg1Target800"),
        .target(name: "Pkg1Target801"),
        .target(name: "Pkg1Target802"),
        .target(name: "Pkg1Target803"),
        .target(name: "Pkg1Target804"),
        .target(name: "Pkg1Target805"),
        .target(name: "Pkg1Target806"),
        .target(name: "Pkg1Target807"),
        .target(name: "Pkg1Target808"),
        .target(name: "Pkg1Target809"),
        .target(name: "Pkg1Target810"),
        .target(name: "Pkg1Target811"),
        .target(name: "Pkg1Target812"),
        .target(name: "Pkg1Target813"),
        .target(name: "Pkg1Target814"),
        .target(name: "Pkg1Target815"),
        .target(name: "Pkg1Target816"),
        .target(name: "Pkg1Target817"),
        .target(name: "Pkg1Target818"),
        .target(name: "Pkg1Target819"),
        .target(name: "Pkg1Target820"),
        .target(name: "Pkg1Target821"),
        .target(name: "Pkg1Target822"),
        .target(name: "Pkg1Target823"),
        .target(name: "Pkg1Target824"),
        .target(name: "Pkg1Target825"),
        .target(name: "Pkg1Target826"),
        .target(name: "Pkg1Target827"),
        .target(name: "Pkg1Target828"),
        .target(name: "Pkg1Target829"),
        .target(name: "Pkg1Target830"),
        .target(name: "Pkg1Target831"),
        .target(name: "Pkg1Target832"),
        .target(name: "Pkg1Target833"),
        .target(name: "Pkg1Target834"),
        .target(name: "Pkg1Target835"),
        .target(name: "Pkg1Target836"),
        .target(name: "Pkg1Target837"),
        .target(name: "Pkg1Target838"),
        .target(name: "Pkg1Target839"),
        .target(name: "Pkg1Target840"),
        .target(name: "Pkg1Target841"),
        .target(name: "Pkg1Target842"),
        .target(name: "Pkg1Target843"),
        .target(name: "Pkg1Target844"),
        .target(name: "Pkg1Target845"),
        .target(name: "Pkg1Target846"),
        .target(name: "Pkg1Target847"),
        .target(name: "Pkg1Target848"),
        .target(name: "Pkg1Target849"),
        .target(name: "Pkg1Target850"),
        .target(name: "Pkg1Target851"),
        .target(name: "Pkg1Target852"),
        .target(name: "Pkg1Target853"),
        .target(name: "Pkg1Target854"),
        .target(name: "Pkg1Target855"),
        .target(name: "Pkg1Target856"),
        .target(name: "Pkg1Target857"),
        .target(name: "Pkg1Target858"),
        .target(name: "Pkg1Target859"),
        .target(name: "Pkg1Target860"),
        .target(name: "Pkg1Target861"),
        .target(name: "Pkg1Target862"),
        .target(name: "Pkg1Target863"),
        .target(name: "Pkg1Target864"),
        .target(name: "Pkg1Target865"),
        .target(name: "Pkg1Target866"),
        .target(name: "Pkg1Target867"),
        .target(name: "Pkg1Target868"),
        .target(name: "Pkg1Target869"),
        .target(name: "Pkg1Target870"),
        .target(name: "Pkg1Target871"),
        .target(name: "Pkg1Target872"),
        .target(name: "Pkg1Target873"),
        .target(name: "Pkg1Target874"),
        .target(name: "Pkg1Target875"),
        .target(name: "Pkg1Target876"),
        .target(name: "Pkg1Target877"),
        .target(name: "Pkg1Target878"),
        .target(name: "Pkg1Target879"),
        .target(name: "Pkg1Target880"),
        .target(name: "Pkg1Target881"),
        .target(name: "Pkg1Target882"),
        .target(name: "Pkg1Target883"),
        .target(name: "Pkg1Target884"),
        // TO COMMENT LINES AFTER THIS COMMENT TO FIX CRASH ON YOUR XCODE 26
        .target(name: "Pkg1Target885"),

//        .target(name: "Pkg1Target886"),
//        .target(name: "Pkg1Target887"),
//        .target(name: "Pkg1Target888"),
//        .target(name: "Pkg1Target889"),
//        .target(name: "Pkg1Target890"),
//        .target(name: "Pkg1Target891"),
//        .target(name: "Pkg1Target892"),
//        .target(name: "Pkg1Target893"),
//        .target(name: "Pkg1Target894"),
//        .target(name: "Pkg1Target895"),
//        .target(name: "Pkg1Target896"),
//        .target(name: "Pkg1Target897"),
//        .target(name: "Pkg1Target898"),
//        .target(name: "Pkg1Target899"),
//        .target(name: "Pkg1Target900"),
//        .target(name: "Pkg1Target901"),
//        .target(name: "Pkg1Target902"),
//        .target(name: "Pkg1Target903"),
//        .target(name: "Pkg1Target904"),
//        .target(name: "Pkg1Target905"),
//        .target(name: "Pkg1Target906"),
//        .target(name: "Pkg1Target907"),
//        .target(name: "Pkg1Target908"),
//        .target(name: "Pkg1Target909"),
//        .target(name: "Pkg1Target910"),
//        .target(name: "Pkg1Target911"),
//        .target(name: "Pkg1Target912"),
//        .target(name: "Pkg1Target913"),
//        .target(name: "Pkg1Target914"),
//        .target(name: "Pkg1Target915"),
//        .target(name: "Pkg1Target916"),
//        .target(name: "Pkg1Target917"),
//        .target(name: "Pkg1Target918"),
//        .target(name: "Pkg1Target919"),
//        .target(name: "Pkg1Target920"),
//        .target(name: "Pkg1Target921"),
//        .target(name: "Pkg1Target922"),
//        .target(name: "Pkg1Target923"),
//        .target(name: "Pkg1Target924"),
//        .target(name: "Pkg1Target925"),
//        .target(name: "Pkg1Target926"),
//        .target(name: "Pkg1Target927"),
//        .target(name: "Pkg1Target928"),
//        .target(name: "Pkg1Target929"),
//        .target(name: "Pkg1Target930"),
//        .target(name: "Pkg1Target931"),
//        .target(name: "Pkg1Target932"),
//        .target(name: "Pkg1Target933"),
//        .target(name: "Pkg1Target934"),
//        .target(name: "Pkg1Target935"),
//        .target(name: "Pkg1Target936"),
//        .target(name: "Pkg1Target937"),
//        .target(name: "Pkg1Target938"),
//        .target(name: "Pkg1Target939"),
//        .target(name: "Pkg1Target940"),
//        .target(name: "Pkg1Target941"),
//        .target(name: "Pkg1Target942"),
//        .target(name: "Pkg1Target943"),
//        .target(name: "Pkg1Target944"),
//        .target(name: "Pkg1Target945"),
//        .target(name: "Pkg1Target946"),
//        .target(name: "Pkg1Target947"),
//        .target(name: "Pkg1Target948"),
//        .target(name: "Pkg1Target949"),
//        .target(name: "Pkg1Target950"),
//        .target(name: "Pkg1Target951"),
//        .target(name: "Pkg1Target952"),
//        .target(name: "Pkg1Target953"),
//        .target(name: "Pkg1Target954"),
//        .target(name: "Pkg1Target955"),
//        .target(name: "Pkg1Target956"),
//        .target(name: "Pkg1Target957"),
//        .target(name: "Pkg1Target958"),
//        .target(name: "Pkg1Target959"),
//        .target(name: "Pkg1Target960"),
//        .target(name: "Pkg1Target961"),
//        .target(name: "Pkg1Target962"),
//        .target(name: "Pkg1Target963"),
//        .target(name: "Pkg1Target964"),
//        .target(name: "Pkg1Target965"),
//        .target(name: "Pkg1Target966"),
//        .target(name: "Pkg1Target967"),
//        .target(name: "Pkg1Target968"),
//        .target(name: "Pkg1Target969"),
//        .target(name: "Pkg1Target970"),
//        .target(name: "Pkg1Target971"),
//        .target(name: "Pkg1Target972"),
//        .target(name: "Pkg1Target973"),
//        .target(name: "Pkg1Target974"),
//        .target(name: "Pkg1Target975"),
//        .target(name: "Pkg1Target976"),
//        .target(name: "Pkg1Target977"),
//        .target(name: "Pkg1Target978"),
//        .target(name: "Pkg1Target979"),
//        .target(name: "Pkg1Target980"),
//        .target(name: "Pkg1Target981"),
//        .target(name: "Pkg1Target982"),
//        .target(name: "Pkg1Target983"),
//        .target(name: "Pkg1Target984"),
//        .target(name: "Pkg1Target985"),
//        .target(name: "Pkg1Target986"),
//        .target(name: "Pkg1Target987"),
//        .target(name: "Pkg1Target988"),
//        .target(name: "Pkg1Target989"),
//        .target(name: "Pkg1Target990"),
//        .target(name: "Pkg1Target991"),
//        .target(name: "Pkg1Target992"),
//        .target(name: "Pkg1Target993"),
//        .target(name: "Pkg1Target994"),
//        .target(name: "Pkg1Target995"),
//        .target(name: "Pkg1Target996"),
//        .target(name: "Pkg1Target997"),
//        .target(name: "Pkg1Target998"),
//        .target(name: "Pkg1Target999"),
//        .target(name: "Pkg1Target1000")
]
let package = Package(
    name: "Pkg1TargetLibrary",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "Pkg1TargetLibrary", targets: targets.map(\.name)),
    ],
    targets: targets
)
